### ISSUE TITLE
Title of page does not reflect WordPress title

### ISSUE THREAD

**Issue by joshsmith** [code-corps/blog.codecorps.org-site#9]
For some reason the page title is not updating to the title set in WordPress. This should definitely be fixed.

**Comment by joshsmith** [comment]
Closed by #12.

**Comment by robconery** [comment]
Can you guys please remove me from this org….

**Comment by joshsmith** [comment]
@robconery you _have_ been removed from the organization. You're watching this repository and others. I can't unwatch repositories for you. You're going to need to do that yourself.
